### PR TITLE
Update MakD to v2.2.0

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
```
* submodules/makd v1.11.2(a8fc56f)...v2.2.0(4209a06) (27 commits)
  > Adapt release notes to new format
  > Add coverage support
  > Add support for specifying a custom package iteration
  > Merge tag v2.1.3 into v2.x.x v2.1.3
  > Merge tag v2.1.2 into v2.x.x v2.1.2
  (...)
```

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
@nemanja-boric-sociomantic : No CI ?

**Comment by nemanja-boric-sociomantic** [comment]
Here's CI you're looking for ;-)

**Comment by mathias-lang-sociomantic** [comment]
And it's even green, wonderful

**Comment by nemanja-boric-sociomantic** [comment]
Thanks!

**Pull request merged**
